[package]
name = "solo-test"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
#glow = "0.11.2"
#eframe = "0.18"

[dependencies.khronos-egl]
version = "4.1.0"
features = [ "static", "no-pkg-config" ]
